name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., production)'
        required: true
        default: 'production'

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Add steps for building your Flutter app, running tests, etc.
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
        
      - name: Install dependencies
        run: flutter pub get

      - name: Build app for production
        run: flutter build apk --release
        
    # Add a step to deploy to Firebase App Distribution for production
      - name: Deploy to Firebase App Distribution (Production)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{secrets.FIREBASE_TOKEN}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: prod # Customize as needed
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: 'Manual production build'